source "https://rubygems.org"

# HamlLiquid is needed for Jekyll 4.x with Liquid templates
gem "jekyll", "~> 4.4"
# gem "github-pages", "~> 232", group: :jekyll_plugins
# gem "minima", "~> 2.5"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "rake"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-relative-links", "~> 0.6"
gem "kramdown", "~> 2.4"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-remote-theme"
end

gem "openssl", "~> 3.3.2"
#
# For better Markdown rendering
gem "markdown", "~> 1.2.1"
